apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
    name: {{ include "sample-dotnet-app.name" . }}
    labels:
        app.kubernetes.io/name: {{ include "sample-dotnet-app.name" . }}
        helm.sh/chart: {{ include "sample-dotnet-app.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        app.kubernetes.io/name: {{ include "sample-dotnet-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ include "sample-dotnet-app.name" . }}
                app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
            containers:
              - name: {{ .Chart.Name }}
                image: " "
                imagePullPolicy: {{ .Values.image.pullPolicy }}
                ports:
                  - name: http
                    containerPort: 8080
                    protocol: TCP
                env:
                  - name: APP_VERSION
                    value: "{{ .Values.app.version }}"
                  - name: VALUES_SERVICE_TYPE
                    value: "{{ .Values.env.valuesServiceType }}"
                volumeMounts:
                  - name: app-config
                    mountPath: /app/config
                    readOnly: true
                livenessProbe:
                    httpGet:
                        path: /health
                        port: 8080
                    initialDelaySeconds: 5
                    periodSeconds: 10
            volumes:
              - name: app-config
                secret:
                    secretName: {{ include "sample-dotnet-app.name" . }}-config
                    items:
                      - key: appusers.json
                        path: appusers.json
    triggers:
      - type: ImageChange
        imageChangeParams:
            automatic: true
            containerNames:
              - {{ .Chart.Name }}
            from:
                kind: ImageStreamTag
                name: "{{ include "sample-dotnet-app.name" . }}:latest"
                namespace: {{ .Release.Namespace }}
      - type: ConfigChange
