# Default values for sample-dotnet-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

build:
  deploy: false

app:
  version: changeme

image:
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

route:
  host: dotnet-ocp-helm-sample-sample-projects.192.168.99.100.nip.io

env:
  valuesServiceType: simple
